회원가입API 틀 완성
leo0842/StudyPot pull request #1
Opened 2021-04-20 14:43 UTC by leo0842

2021-04-20 14:46 UTC, bum752 requested changes

2021-04-20 14:46 UTC, bum752 commented on back/src/main/java/com/studypot/back/applications/UserService.java
> +  @Autowired
`@Autowired` 는 없어도 생성자를 통해 `userRepository`가 주입

2021-04-20 14:46 UTC, bum752 commented on back/src/main/java/com/studypot/back/applications/UserService.java
> +        .password(password)
아직 안한거겠지만 비밀번호 암호화 필요

2021-04-20 14:46 UTC, bum752 commented on back/src/main/java/com/studypot/back/domain/User.java
> +@AllArgsConstructor
builder 사용 외 생성자를 이용한 객체 생성이 없어 보이는데 두 어노테이션이 있을 필요가 있을지...?

2021-04-20 14:46 UTC, bum752 commented on back/src/main/java/com/studypot/back/domain/User.java
> +  @GeneratedValue
id 생성 방법이 필요

2021-04-20 14:46 UTC, bum752 commented on back/src/main/java/com/studypot/back/interfaces/UserController.java
> +  @Autowired
생성자 주입으로 바꾸면 좋을 듯

2021-04-20 14:46 UTC, bum752 commented on back/src/main/java/com/studypot/back/interfaces/UserController.java
> +    return ResponseEntity.created(new URI(url)).body("{}");
`ResponseEntity` 를 응답하지 않고 응답상태만 응답하는 방법도 좋아보임
리다이렉트 url은 프론트에서 충분히 처리 가능

2021-04-21 14:19 UTC, leo0842 commented
도움 많이 받았습니다.

2021-04-21 14:19 UTC, closed without merging